apiVersion: apps/v1
kind: Deployment
metadata:
  name: tks-cluster-lcm
  namespace: tks
spec:
  template:
    spec:
      containers:
        - name: tks-cluster-lcm
          env:
          - name: LOG_LEVEL
            value: DEBUG
          args: [
            "-port", "9110",
            "-info-address", "tks-info.tks.svc",
            "-info-port", "9110",
            "-contract-address", "tks-contract.tks.svc",
            "-contract-port", "9110",
            "-argo-address", "argo-workflows-operator-server.argo.svc",
            "-argo-port", "2746",
            "-revision", "main",
            "-git-account", "demo-decapod10",
          ]

