apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
patchesStrategicMerge:
- patch.yaml
resources:
- ../../base
images:
- name: docker.io/sktcloud/tks-info
  newTag: 64e441ffcb83b1a05fa7f9c3cbbc713f2212d800
