---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tks-info
  namespace: tks
spec:
  template:
    spec:
      containers:
        - name: tks-info
          env:
          - name: LOG_LEVEL
            value: DEBUG
          args: [
            "-contract-address", "tks-contract.tks.svc",
            "-contract-port", "9110",
            "-dbhost", "postgresql.decapod-db.svc",
            "-port", "9110",
            "-dbhost", "postgresql.decapod-db.svc",
            "-dbport", "5432",
            "-dbuser", "tksuser",
            "-dbpassword", "tkspassword"
          ]
---
