apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tks-cluster-lcm 
  namespace: tks
spec:
  destination:
    namespace: tks
    server: https://kubernetes.default.svc 
  project: tks-apis
  source:
    repoURL: 'https://github.com/ktkfree/tks-manifests'
    path: development/tks-cluster-lcm/manifests
    targetRevision: HEAD
  syncPolicy:
    automated: {}

