replicaCount: 1

namespace: tks

image:
  repository: docker.io/sktcloud/tks-cluster-lcm
  pullPolicy: Always
  tag: "latest"

imagePullSecrets: []
nameOverride: "tks-cluster-lcm"
fullnameOverride: "tks-cluster-lcm"

serviceAccount:
  create: true
  annotations: {}
  name: "tks-cluster-lcm"

args:
  port: 9110
  tksInfoAddress: tks-info.tks.svc
  tksInfoPort: 9110
  tksContractAddress: tks-contract.tks.svc
  tksContractPort: 9110
  argoAddress: argo-workflows-operator-server.argo.svc
  argoPort: 2746 
  revision: main
  gitAccount: tks-management

podAnnotations: {}

podSecurityContext: {}

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: LoadBalancer
  port: 9110

ingress:
  enabled: false
  annotations: {}
  hosts:
    - host: chart-example.local
      paths: []
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

tolerations: []

affinity: {}
