apiVersion: v1
kind: Service
metadata:
  name: tks-admin-console
  labels:
    app: tks-admin-console
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: tks-admin-console
