---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tks-contract
  namespace: tks
spec:
  template:
    spec:
      containers:
        - name: tks-contract
          env:
          - name: LOG_LEVEL
            value: DEBUG
          args: [
            "-port", "9110",
            "-dbhost", "postgresql.decapod-db.svc",
            "-dbport", "5432",
            "-dbuser", "tksuser",
            "-dbpassword", "tkspassword",
            "-info-address", "tks-info.tks.svc",
            "-info-port", "9110",
            "-argo-address", "argo-workflows-operator-server.argo.svc",
            "-argo-port", "2746",
            "-revision", "main"
          ]
---
