---
# Source: tks-batch/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tks-batch
  labels:
    helm.sh/chart: tks-batch-0.1.0
    app.kubernetes.io/service: tks
    app.kubernetes.io/name: tks-batch
    app.kubernetes.io/version: "0.1.0"
    app.kubernetes.io/managed-by: Helm
---
# Source: tks-batch/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: tks-batch
  namespace: tks
  labels:
    helm.sh/chart: tks-batch-0.1.0
    app.kubernetes.io/service: tks
    app.kubernetes.io/name: tks-batch
    app.kubernetes.io/version: "0.1.0"
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
    - port: 9110
      targetPort: 9110
      protocol: TCP
  selector:
    app.kubernetes.io/service: tks
    app.kubernetes.io/name: tks-batch
---
# Source: tks-batch/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tks-batch
  namespace: tks
  labels:
    helm.sh/chart: tks-batch-0.1.0
    app.kubernetes.io/service: tks
    app.kubernetes.io/name: tks-batch
    app.kubernetes.io/version: "0.1.0"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/service: tks
      app.kubernetes.io/name: tks-batch
  template:
    metadata:
      labels:
        app.kubernetes.io/service: tks
        app.kubernetes.io/name: tks-batch
    spec:
      serviceAccountName: tks-batch
      securityContext:
        {}
      containers:
        - name: tks-batch
          securityContext:
            {}
          image: "docker.io/sktcloud/tks-batch:latest"
          imagePullPolicy: Always
          ports:
            - name: tks-batch
              containerPort: 9110
              protocol: TCP
          command:
            - /app/server
          env:
          - name: LOG_LEVEL
            value: DEBUG
          args: [
            "-port", "9110",
            "-dbhost", "postgresql.decapod-db.svc",
            "-dbport", "5432",
            "-dbuser", "tksuser",
            "-dbpassword", "tkspassword",
            "-argo-address", "argo-workflows-operator-server.argo.svc",
            "-argo-port", "2746"
          ]
          resources:
            null
