apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
patchesStrategicMerge:
- patch.yaml
resources:
- ../../base
images:
- name: docker.io/sktcloud/tks-batch
  newTag: e56ed59a3aa2da5eb3575b4417734cf405f796e3
