# argocd app create tks-contract --repo https://github.com/openinfradev/tks-manifests --path tks-contract/overlay/development --dest-namespace tks --dest-server https://kubernetes.default.svc --revision-history-limit 3 --sync-policy automated --project tks-apis
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tks-contract
  namespace: tks
spec:
  destination:
    namespace: tks
    server: https://kubernetes.default.svc 
  project: tks-apis
  source:
    repoURL: 'https://github.com/openinfradev/tks-manifests'
    path: tks-contract/overlay/development
    targetRevision: HEAD
  syncPolicy:
    automated: {}
  revisionHistoryLimit: 3

