---
# Source: tks-cluster-lcm/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tks-cluster-lcm
  labels:
    helm.sh/chart: tks-cluster-lcm-0.1.0
    app.kubernetes.io/service: tks
    app.kubernetes.io/name: tks-cluster-lcm
    app.kubernetes.io/version: "0.1.0"
    app.kubernetes.io/managed-by: Helm
---
# Source: tks-cluster-lcm/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: tks-cluster-lcm
  namespace: tks
  labels:
    helm.sh/chart: tks-cluster-lcm-0.1.0
    app.kubernetes.io/service: tks
    app.kubernetes.io/name: tks-cluster-lcm
    app.kubernetes.io/version: "0.1.0"
    app.kubernetes.io/managed-by: Helm
spec:
  type: LoadBalancer
  ports:
    - port: 9110
      targetPort: 9110
      protocol: TCP
  selector:
    app.kubernetes.io/service: tks
    app.kubernetes.io/name: tks-cluster-lcm
---
# Source: tks-cluster-lcm/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tks-cluster-lcm
  namespace: tks
  labels:
    helm.sh/chart: tks-cluster-lcm-0.1.0
    app.kubernetes.io/service: tks
    app.kubernetes.io/name: tks-cluster-lcm
    app.kubernetes.io/version: "0.1.0"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/service: tks
      app.kubernetes.io/name: tks-cluster-lcm
  template:
    metadata:
      labels:
        app.kubernetes.io/service: tks
        app.kubernetes.io/name: tks-cluster-lcm
    spec:
      serviceAccountName: tks-cluster-lcm
      securityContext:
        {}
      containers:
        - name: tks-cluster-lcm
          securityContext:
            {}
          image: "docker.io/sktcloud/tks-cluster-lcm:f23cfc43cea5a3b35ddf8f18af52e89bb51e41d8"
          imagePullPolicy: Always
          ports:
            - name: tks-cluster-lcm
              containerPort: 9110
              protocol: TCP
          command:
            - /app/server
          env:
          - name: LOG_LEVEL
            value: DEBUG
          args: [
            "-port", "9110",
            "-info-address", "tks-info.tks.svc",
            "-info-port", "9110",
            "-contract-address", "tks-contract.tks.svc",
            "-contract-port", "9110",
            "-argo-address", "argo-workflows-operator-server.argo.svc",
            "-argo-port", "2746",
            "-revision", "main",
            "-git-account", "tks-management",
          ]
          resources:
            {}
